# Generated by Django 5.0.4 on 2024-04-24 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
                ('details', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='producttable',
            old_name='product_category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='producttable',
            old_name='product_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='producttable',
            old_name='product_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='producttable',
            old_name='product_price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='producttable',
            old_name='product_seller',
            new_name='seller',
        ),
        migrations.RemoveField(
            model_name='sellertable',
            name='seller_phone',
        ),
    ]
